#!/usr/bin/env bash
# SwingSight Phase 2 — interactive provisioning helper.
#
# Reads setup.env (created from setup.env.example), PROMPTS for anything still
# blank, auto-generates the two shared secrets, then writes the files and offers
# to run the Supabase steps. Safe to re-run: it remembers answers in setup.env,
# and every CLI action is opt-in (default No).
#
#   ./scripts/setup.sh
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

bold()  { printf '\033[1m%s\033[0m\n' "$1"; }
ok()    { printf '  \033[32m✓\033[0m %s\n' "$1"; }
info()  { printf '  • %s\n' "$1"; }

bold "SwingSight Phase 2 setup"

# --- load (or seed) setup.env ---------------------------------------------
if [[ ! -f setup.env ]]; then
  cp setup.env.example setup.env
  info "Created setup.env from the template."
fi
set -a; # shellcheck disable=SC1091
source ./setup.env
set +a

# ask VAR "human prompt" ["default"]  — prompt only if the var is empty.
ask() {
  local var="$1" prompt="$2" default="${3:-}" current
  current="${!var:-}"
  if [[ -n "$current" ]]; then return; fi
  if [[ -n "$default" ]]; then
    read -rp "  $prompt [$default]: " current
    current="${current:-$default}"
  else
    read -rp "  $prompt: " current
  fi
  printf -v "$var" '%s' "$current"
}

bold $'\n1) Supabase  (supabase.com → your project → Settings → API / General)'
ask SUPABASE_PROJECT_REF "Project ref"
ask SUPABASE_URL         "Project URL" "https://${SUPABASE_PROJECT_REF}.supabase.co"
ask SUPABASE_ANON_KEY    "anon public key"

bold $'\n2) Cloudflare R2  (see supabase/r2/README.md)'
ask R2_ACCOUNT_ID        "R2 account id"
ask R2_ACCESS_KEY_ID     "R2 access key id"
ask R2_SECRET_ACCESS_KEY "R2 secret access key"
ask R2_BUCKET            "R2 bucket" "swingsight-proto"
ask R2_ENDPOINT          "R2 S3 endpoint" "https://${R2_ACCOUNT_ID}.eu.r2.cloudflarestorage.com"

ask SAMPLE_CLIP          "Sample clip path" "$HOME/Code/Swing_Prototype/data/videos/IMG_5736.mov"

# --- auto-generate the shared secrets if blank ----------------------------
if [[ -z "${WEBHOOK_SECRET:-}" ]]; then WEBHOOK_SECRET="$(openssl rand -hex 32)"; ok "Generated WEBHOOK_SECRET"; fi
if [[ -z "${INVOKER_TOKEN:-}" ]]; then INVOKER_TOKEN="$(openssl rand -hex 32)"; ok "Generated INVOKER_TOKEN"; fi

# --- persist everything back to setup.env (gitignored) --------------------
cat > setup.env <<EOF
# SwingSight Phase 2 provisioning values (filled by scripts/setup.sh). GITIGNORED.
SUPABASE_PROJECT_REF=$SUPABASE_PROJECT_REF
SUPABASE_URL=$SUPABASE_URL
SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY
R2_ACCOUNT_ID=$R2_ACCOUNT_ID
R2_ACCESS_KEY_ID=$R2_ACCESS_KEY_ID
R2_SECRET_ACCESS_KEY=$R2_SECRET_ACCESS_KEY
R2_BUCKET=$R2_BUCKET
R2_ENDPOINT=$R2_ENDPOINT
WEBHOOK_SECRET=$WEBHOOK_SECRET
INVOKER_TOKEN=$INVOKER_TOKEN
WORKER_URL=${WORKER_URL:-}
SAMPLE_CLIP=$SAMPLE_CLIP
EOF
ok "Saved setup.env"

# --- write app/.env (public values only) ----------------------------------
cat > app/.env <<EOF
# Generated by scripts/setup.sh — public values only (safe in the bundle).
EXPO_PUBLIC_SUPABASE_URL=$SUPABASE_URL
EXPO_PUBLIC_SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY
EOF
ok "Wrote app/.env"

# --- write the Vault SQL (paste into the dashboard SQL editor) -------------
cat > supabase/vault-secrets.sql <<EOF
-- SwingSight — Vault secrets that power the DB → Edge Function webhook.
-- Paste into the Supabase dashboard SQL editor AFTER 'supabase db push'.
select vault.create_secret('$SUPABASE_URL', 'edge_function_base_url', 'SwingSight edge base url');
select vault.create_secret('$WEBHOOK_SECRET', 'on_swing_insert_secret', 'SwingSight webhook secret');
EOF
ok "Wrote supabase/vault-secrets.sql"

# --- optional CLI actions (each opt-in) -----------------------------------
confirm() { read -rp "  $1 [y/N]: " a; [[ "$a" == [yY] ]]; }

bold $'\n3) Supabase CLI actions (optional — say N to do them yourself later)'

if confirm "Run 'supabase link --project-ref $SUPABASE_PROJECT_REF' now? (needs 'supabase login')"; then
  supabase link --project-ref "$SUPABASE_PROJECT_REF" && ok "Linked"
fi

if confirm "Run 'supabase db push' (apply the schema)?"; then
  supabase db push && ok "Schema pushed"
fi

if confirm "Set the Edge Function secrets now?"; then
  supabase secrets set \
    R2_ACCOUNT_ID="$R2_ACCOUNT_ID" \
    R2_ACCESS_KEY_ID="$R2_ACCESS_KEY_ID" \
    R2_SECRET_ACCESS_KEY="$R2_SECRET_ACCESS_KEY" \
    R2_BUCKET="$R2_BUCKET" \
    R2_ENDPOINT="$R2_ENDPOINT" \
    ON_SWING_INSERT_SECRET="$WEBHOOK_SECRET" \
    WORKER_INVOKER_TOKEN="$INVOKER_TOKEN" \
    ${WORKER_URL:+WORKER_URL="$WORKER_URL"} \
    && ok "Secrets set"
fi

if confirm "Deploy the Edge Functions now?"; then
  supabase functions deploy upload-url
  supabase functions deploy on-swing-insert
  ok "Functions deployed"
fi

# --- what's left (manual) --------------------------------------------------
bold $'\nRemaining manual steps:'
info "Enable anon auth: Dashboard → Authentication → Sign In/Up → Anonymous sign-ins = ON"
info "Vault: paste supabase/vault-secrets.sql into the dashboard SQL editor"
info "R2 lifecycle: see supabase/r2/README.md step 3"
info "Then run the checkpoint:"
echo

bold "Run the checkpoint now?"
if confirm "Upload the real clip + fire the webhook?"; then
  SUPABASE_URL="$SUPABASE_URL" SUPABASE_ANON_KEY="$SUPABASE_ANON_KEY" \
  SAMPLE_CLIP="${SAMPLE_CLIP/#\~/$HOME}" \
    node supabase/scripts/checkpoint-upload.mjs
  echo
  info "Confirm the webhook: supabase functions logs on-swing-insert  → 'worker /analyze -> 501'"
fi

bold $'\nDone.'
